/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Lenovo
 */
public class GUIKalkulator extends javax.swing.JFrame {

    /**
     * Creates new form GUIKalkulator
     */
    public GUIKalkulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        hasilTF = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        tujuhBT = new javax.swing.JButton();
        delapanBT = new javax.swing.JButton();
        sembilanBT = new javax.swing.JButton();
        empatBT = new javax.swing.JButton();
        limaBT = new javax.swing.JButton();
        enamBT = new javax.swing.JButton();
        tigaBT = new javax.swing.JButton();
        komaBT = new javax.swing.JButton();
        hapusBT = new javax.swing.JButton();
        nolBT = new javax.swing.JButton();
        satuBT = new javax.swing.JButton();
        duaBT = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        tambahBT = new javax.swing.JButton();
        kurangBT = new javax.swing.JButton();
        kaliBT = new javax.swing.JButton();
        bagiBT = new javax.swing.JButton();
        hasilBT = new javax.swing.JButton();
        persenBT = new javax.swing.JButton();
        exitBT = new javax.swing.JButton();
        backspaceBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        hasilTF.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        hasilTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hasilTF)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hasilTF, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tujuhBT.setText("7");
        tujuhBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tujuhBTActionPerformed(evt);
            }
        });

        delapanBT.setText("8");
        delapanBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delapanBTActionPerformed(evt);
            }
        });

        sembilanBT.setText("9");
        sembilanBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sembilanBTActionPerformed(evt);
            }
        });

        empatBT.setText("4");
        empatBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empatBTActionPerformed(evt);
            }
        });

        limaBT.setText("5");
        limaBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limaBTActionPerformed(evt);
            }
        });

        enamBT.setText("6");
        enamBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enamBTActionPerformed(evt);
            }
        });

        tigaBT.setText("3");
        tigaBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tigaBTActionPerformed(evt);
            }
        });

        komaBT.setText(".");
        komaBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                komaBTActionPerformed(evt);
            }
        });

        hapusBT.setText("C");
        hapusBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBTActionPerformed(evt);
            }
        });

        nolBT.setText("0");
        nolBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nolBTActionPerformed(evt);
            }
        });

        satuBT.setText("1");
        satuBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satuBTActionPerformed(evt);
            }
        });

        duaBT.setText("2");
        duaBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duaBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(satuBT, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(duaBT, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tigaBT, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tujuhBT, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(delapanBT, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sembilanBT, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(empatBT, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(limaBT, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(enamBT, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(komaBT, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nolBT, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hapusBT, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tujuhBT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delapanBT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sembilanBT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empatBT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limaBT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enamBT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(satuBT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(duaBT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tigaBT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(komaBT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nolBT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hapusBT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        tambahBT.setText("+");
        tambahBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBTActionPerformed(evt);
            }
        });

        kurangBT.setText("-");
        kurangBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurangBTActionPerformed(evt);
            }
        });

        kaliBT.setText("*");
        kaliBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaliBTActionPerformed(evt);
            }
        });

        bagiBT.setText("/");
        bagiBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagiBTActionPerformed(evt);
            }
        });

        hasilBT.setText("=");
        hasilBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilBTActionPerformed(evt);
            }
        });

        persenBT.setText("%");
        persenBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persenBTActionPerformed(evt);
            }
        });

        exitBT.setText("E");
        exitBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTActionPerformed(evt);
            }
        });

        backspaceBT.setText("B");
        backspaceBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backspaceBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tambahBT, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kurangBT, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(kaliBT, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bagiBT, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(hasilBT, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(persenBT, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(backspaceBT, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exitBT, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahBT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kurangBT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kaliBT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bagiBT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hasilBT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(persenBT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backspaceBT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitBT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    String bilangan="";
    Double hasil, bil1, bil2,hapus1;
    int pilih;
    
    private void hasilTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilTFActionPerformed

    private void nolBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nolBTActionPerformed
        // TODO add your handling code here:
        bilangan+="0";
        hasilTF.setText(bilangan);
    }//GEN-LAST:event_nolBTActionPerformed

    private void satuBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satuBTActionPerformed
        // TODO add your handling code here:
        bilangan+="1";
        hasilTF.setText(bilangan);
    }//GEN-LAST:event_satuBTActionPerformed

    private void duaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duaBTActionPerformed
        // TODO add your handling code here:
        bilangan+="2";
        hasilTF.setText(bilangan);
    }//GEN-LAST:event_duaBTActionPerformed

    private void tigaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tigaBTActionPerformed
        // TODO add your handling code here:
        bilangan+="3";
        hasilTF.setText(bilangan);
    }//GEN-LAST:event_tigaBTActionPerformed

    private void empatBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empatBTActionPerformed
        // TODO add your handling code here:
        bilangan+="4";
        hasilTF.setText(bilangan);
    }//GEN-LAST:event_empatBTActionPerformed

    private void limaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limaBTActionPerformed
        // TODO add your handling code here:
        bilangan+="5";
        hasilTF.setText(bilangan);
    }//GEN-LAST:event_limaBTActionPerformed

    private void enamBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enamBTActionPerformed
        // TODO add your handling code here:
        bilangan+="6";
        hasilTF.setText(bilangan);
    }//GEN-LAST:event_enamBTActionPerformed

    private void tujuhBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tujuhBTActionPerformed
        // TODO add your handling code here:
        bilangan+="7";
        hasilTF.setText(bilangan);
    }//GEN-LAST:event_tujuhBTActionPerformed

    private void delapanBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delapanBTActionPerformed
        // TODO add your handling code here:
        bilangan+="8";
        hasilTF.setText(bilangan);
    }//GEN-LAST:event_delapanBTActionPerformed

    private void sembilanBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sembilanBTActionPerformed
        // TODO add your handling code here:
        bilangan+="9";
        hasilTF.setText(bilangan);
    }//GEN-LAST:event_sembilanBTActionPerformed

    private void hapusBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBTActionPerformed
        // TODO add your handling code here:
        hasilTF.setText(null);
        bil1=0.0;
        bil2=0.0;
        bilangan="";
    }//GEN-LAST:event_hapusBTActionPerformed

    private void tambahBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBTActionPerformed
        // TODO add your handling code here:
        bil1 = Double.parseDouble(bilangan);
        hasilTF.setText("+");
        bilangan="";
        pilih=1;
    }//GEN-LAST:event_tambahBTActionPerformed

    private void kurangBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurangBTActionPerformed
        // TODO add your handling code here:
        bil1 = Double.parseDouble(bilangan);
        hasilTF.setText("-");
        bilangan="";
        pilih=2;
    }//GEN-LAST:event_kurangBTActionPerformed

    private void kaliBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaliBTActionPerformed
        // TODO add your handling code here:
        bil1 = Double.parseDouble(bilangan);
        hasilTF.setText("*");
        bilangan="";
        pilih=3;
    }//GEN-LAST:event_kaliBTActionPerformed

    private void bagiBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagiBTActionPerformed
        // TODO add your handling code here:
        bil1 = Double.parseDouble(bilangan);
        hasilTF.setText("/");
        bilangan="";
        pilih=4;
    }//GEN-LAST:event_bagiBTActionPerformed

    private void persenBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_persenBTActionPerformed
        // TODO add your handling code here:
        bil1 = Double.parseDouble(bilangan);
        hasilTF.setText("%");
        pilih=5;
    }//GEN-LAST:event_persenBTActionPerformed

    private void hasilBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilBTActionPerformed
        // TODO add your handling code here:
        switch(pilih){
            case 1:
                bil2 = Double.parseDouble(String.valueOf(hasilTF.getText()));
                hasil = bil1 + bil2;
                bilangan = Double.toString(hasil);
            break;
            case 2:
                bil2 = Double.parseDouble(String.valueOf(hasilTF.getText()));
                hasil = bil1 - bil2;
                bilangan = Double.toString(hasil);
            break;
            case 3:
                bil2 = Double.parseDouble(String.valueOf(hasilTF.getText()));
                hasil = bil1 * bil2;
                bilangan = Double.toString(hasil);
            break;
            case 4:
                bil2 = Double.parseDouble(String.valueOf(hasilTF.getText()));
                hasil = bil1 / bil2;
                bilangan = Double.toString(hasil);
            break;
            case 5:
                hasil = bil1 / 100;
                bilangan = Double.toString(hasil);
            break;
        }
        hasilTF.setText(bilangan);
    }//GEN-LAST:event_hasilBTActionPerformed

    private void komaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_komaBTActionPerformed
        // TODO add your handling code here:
        bilangan+=".";
        hasilTF.setText(bilangan);
    }//GEN-LAST:event_komaBTActionPerformed

    private void backspaceBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backspaceBTActionPerformed
        // TODO add your handling code here:
        if (hasilTF.getText().length() > 0) {
                    StringBuilder strB = new StringBuilder(hasilTF.getText());
                    strB.deleteCharAt(hasilTF.getText().length()-1);
                    
                    bilangan = strB.toString();
                    hasilTF.setText(bilangan);
                }
    }//GEN-LAST:event_backspaceBTActionPerformed

    private void exitBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIKalkulator().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backspaceBT;
    private javax.swing.JButton bagiBT;
    private javax.swing.JButton delapanBT;
    private javax.swing.JButton duaBT;
    private javax.swing.JButton empatBT;
    private javax.swing.JButton enamBT;
    private javax.swing.JButton exitBT;
    private javax.swing.JButton hapusBT;
    private javax.swing.JButton hasilBT;
    private javax.swing.JTextField hasilTF;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton kaliBT;
    private javax.swing.JButton komaBT;
    private javax.swing.JButton kurangBT;
    private javax.swing.JButton limaBT;
    private javax.swing.JButton nolBT;
    private javax.swing.JButton persenBT;
    private javax.swing.JButton satuBT;
    private javax.swing.JButton sembilanBT;
    private javax.swing.JButton tambahBT;
    private javax.swing.JButton tigaBT;
    private javax.swing.JButton tujuhBT;
    // End of variables declaration//GEN-END:variables
}
